cloud-bastion
Otus-DevOps-2020-02/vvlliicc_infra pull request #2
Opened 2020-03-22 14:42 UTC by vvlliicc

2020-03-22 15:24 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Не хватает описания в пр. Так же проверьте структуру каталога в репозитории. Она должна быть такая же как и в методичке. ДЗ возвращаю на доработку.

2020-03-22 17:41 UTC, mrgreyves requested changes
!!! =)

2020-03-25 05:18 UTC, mrgreyves requested changes
Здравствуйте!) Описания все так же нет.
![image](https://user-images.githubusercontent.com/34331259/77504375-32bf9e80-6e71-11ea-93ac-421227662ffb.png)

2020-03-25 13:57 UTC, vvlliicc commented
# Выполнено ДЗ № 3

 - [ + ] Основное ДЗ
 - [ -  ] Задание со *

## В процессе сделано:
1.Зарегистрировался в GCP
 2.Настроен GCP
3.Добавление хоста bastion с внешним IP адресом
4.Добавление хоста someinternalhost без внешнего IP адреса 
5.Настроен удалённый доступ
6.Установлен pritunl и настроен для добавления пользователей 

## Как запустить проект:
 - На хосте с статическим ИП должен быть запущен Pritгnl 

## Как проверить работоспособность:
 - Необходимо добавить пользователя и скачать его конфиг , далее скачать клиент и добавить скачанный конфиг пользователя

## PR checklist
 - [ + ] Выставил label с номером домашнего задания
 - [ + ] Выставил label с темой домашнего задания

2020-08-20 14:16 UTC, vvlliicc commented
test

2020-08-20 15:14 UTC, vvlliicc reviewed
test

2020-08-24 11:31 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-08-24 13:08 UTC, merged