Cloud testapp
Otus-DevOps-2020-02/vvlliicc_infra pull request #3
Opened 2020-03-25 15:24 UTC by vvlliicc

# Выполнено ДЗ №4

 - [ + ] Основное ДЗ
 - [ +- ] Задание со *

## В процессе сделано:
 - Установили виртуальный сервер через консоль gcp
 - Установили необходимое ПО для работы прелдожения
 - Скачали и запустили преложение
 - Создали правило Firewall для работы приложения

## Как запустить проект:
 - puma -d

## Как проверить работоспособность:
 - ps aux | grep puma
 - перейти по ссылке  - http://34.91.217.122:9292/

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2020-03-25 19:24 UTC, mrgreyves requested changes
Здравствуйте!) К сожалению у вас тесты красные. Оставил комментарий к файлу. ДЗ возвращаю на доработку.

2020-03-25 19:24 UTC, mrgreyves commented on install_mongodb.sh
> +0xd68fa50fea312927
Перепроверьте скрипт, съехали переносы =)

2020-03-26 09:36 UTC, vvlliicc commented on install_mongodb.sh
> +0xd68fa50fea312927
Спасибо большое, исправил))

2020-03-28 13:08 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно вернуть директорию VPN обратно в репозиторий =)

2020-04-01 13:57 UTC, mrgreyves approved these changes
Здравствуйте!) А вот теперь точно апрув!)

2020-08-20 15:12 UTC, merged