Terraform 1
Otus-DevOps-2020-02/vvlliicc_infra pull request #5
Opened 2020-04-21 13:56 UTC by vvlliicc

# Выполнено ДЗ № terraform
 - [ + ] Основное ДЗ
 - [ - ] Задание со *

## В процессе сделано:
 - установили terraform
 - создали файл настроек main.tf

## Как запустить проект:
 - terraform init
 - terraform plan
 - terraform apply
## Как проверить работоспособность:
 - Перейти по ссылке http://localhost:9292

## PR checklist
 - [+ ] Выставил label с номером домашнего задания
 - [ +] Выставил label с темой домашнего задания

2020-04-22 16:26 UTC, mrgreyves requested changes
Здравствуйте!) Оставил комментарий к файлу. ДЗ возвращаю на доработку =)

2020-04-22 16:26 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = "0.12"
Попробуйте указать версию вот так required_version = "~> 0.12.19"

2020-04-22 16:37 UTC, vvlliicc commented on terraform/main.tf
> +  required_version = "0.12"
Здравствуйте, установил как вы указала)

2020-04-23 11:07 UTC, mrgreyves requested changes
Здравствуйте!) Я там еще к одному файлу сделал пометку. Осталось внести совсем маленький фикс =)

2020-04-23 11:07 UTC, mrgreyves commented on terraform/main.tf
> +  credentials = file("/home/viktor/Downloads/Infra-39d53002ed4b.json")
А вот это лучше удалить. По этому тесты и валятся. Файла то в репозитории нет =)

2020-04-23 12:37 UTC, vvlliicc commented on terraform/main.tf
> +  credentials = file("/home/viktor/Downloads/Infra-39d53002ed4b.json")
Да изменил, тест прошел) спасибо большое))

2020-04-23 12:55 UTC, mrgreyves approved these changes
А вот теперь точно апрув!) У вас там образовался небольшой мерж конфликт, доступен интерфейс для решения. Думаю там не очень страшно =)

2020-08-24 11:35 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-08-24 14:03 UTC, merged